subsystem: "arm.winch.Winch"
description: "All motors used in the robot winch mechanism live here for the winch component"
winch:
    channel: 40
    type: "motor.SparkMax"
    inverted: False
    motorType: "kBrushless"
    pid: Null