subsystem: "actuators.breadboxArmController.ArmController"
name: "Dumbo Arm Controller"
description:  "Handles the rotation, extension, and manipulator"

setArmAnglesDegrees:
    frontBottom: 0
    frontMiddle: 30
    frontTop: 60
    top: 100
    backTop: 161.0
    backMiddle: 196.0
    backBottom: 200

#TODO once arm elevator if set, control here
setArmLengthUnits:
    low: 0
    mid: 5
    high: 10
