subsystem: "actuators.breadboxArmController.ArmController"
name: "Dumbo Arm Controller"
description:  "Handles the rotation, extension, and manipulator"

setArmAnglesDegrees:
    frontBottom: 4
    frontMiddle: 30
    frontTop: 175
    top: 100
    backTop: 161.0
    backMiddle: 196.0
    backBottom: 208
