subsystem: "actuators.dumboArm.Arm"
name: "arm"
description: "Arm for Dumbo. Future may be more general arm"

armFeedFordward:
    kS: -0.10263
    kG: 0.0094089
    kV: 24.416
    kA: 4.1812

motor:
  channel: 40
  #type: "motor.SparkMax"
  inverted: True
  motorType: "kBrushless"
  sensorPhase: True
  pid: Null

encoder:
  #type: "sensor.wpilib.DutyCycleEncoder"
  channel: 0
  offset: 0.0
  unitsPerRotation: 6.28318530718 #2Pi
  minDutyCycle: 0.0
  maxDutyCycle: 1.0