subsystem: "arm.grader.Grader"
description: "All motors used in the robot grader mechanism live here for the grader component"
grader:
    channel: 40
    type: "motor.SparkMax"
    inverted: False
    motorType: "kBrushless"
    pid: Null