subsystem: "drivetrains.westcoast.Westcoast"
description: "All motors used in the drive train live here"

rightMotor:
  channel: 30
  type: "motor.CANTalonFX"
  inverted: False
  pid:
    kP: 0.001
    kI: 0
    kD: 0
    kF: 0
    controlType: "PercentOutput"
    sensorPhase: True
    kPreScale: 2
    feedbackDevice: "IntegratedSensor"
  currentLimits:
    triggerThresholdCurrent: 60
    triggerThresholdTime: 50
    currentLimit: 40
rightFollower:
  channel: 31
  masterChannel: 30
  type: "motor.CANTalonFXFollower"
  inverted: False
  currentLimits:
    triggerThresholdCurrent: 60
    triggerThresholdTime: 50
    currentLimit: 40

leftMotor:
  channel: 20
  type: "motor.CANTalonFX"
  inverted: True
  pid:
    kP: 0.001
    kI: 0
    kD: 0
    kF: 0
    controlType: "PercentOutput"
    sensorPhase: True
    kPreScale: 2
    feedbackDevice: "IntegratedSensor"
  currentLimits:
    triggerThresholdCurrent: 60
    triggerThresholdTime: 50
    currentLimit: 40

leftFollower:
  channel: 21
  masterChannel: 20
  type: "motor.CANTalonFXFollower"
  currentLimits:
    triggerThresholdCurrent: 60
    triggerThresholdTime: 50
    currentLimit: 40
  inverted: True

motorGroup:
#TODO add motor group factory
  type: "motor.MotorControllerGroup"
  motors:
    - "leftMotor"
    - "leftFollower"
gyro:
  type: "sensor.navx"
  required: False