details: "Drive Train For Dumbo with elevator on arm and actuator"
cameraServer: True #
# Start camera server for USB cameras
#CameraServer.launch()

subsystems:
    drivetrain:
      required: true
      type: yaml
      file: "talonFXTankDrive.yml"
    armRotation:
       required: False
       type: yaml
       file: "dumboArmRotation.yml"
    grabber:
      required: False
      type: yaml
      file: "grader.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"
