details: "Drive Train only robot with 4 talon SRX in tank drive"
cameraServer: True #
# Start camera server for USB cameras
#CameraServer.launch()

subsystems:
    drivetrain:
      required: true
      type: yaml
      file: "talonFXTankDrive.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"
