details: "Drive Train only robot with 2 talon SRX in tank drive"
cameraServer: True #
# Start camera server for USB cameras
#CameraServer.launch()

subsystems:
    drivetrain:
      required: true
      type: yaml
      file: "talonSRXTankDriveSmall.yml"
    #TODO flesh out support for non required and missing
    #newSub:
    #  type: newFile
    #  file: "newSubsystem.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"