details: "Config for Teapot robot. Currently only supports drive train in 2023"
cameraServer: True #
# Start camera server for USB cameras
#CameraServer.launch()

subsystems:
    drivetrain:
      required: true
      type: yaml
      file: "talonTankDrive.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"
