details: ""

subsystems:
    drivetrain:
      required: true
      type: yaml
      file: "talonTankDrive.yml"
    Arm:
      required: true
      type: yaml
      file: "armwinch.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"
    armController:
      name: "moveArm"
      subsystems:
        - "Arm"