details: ""

subsystems:
    Arm:
      required: true
      type: yaml
      file: "armwinch.yml"
    #TODO flesh out support for non required and missing
    #newSub:
    #  type: newFile
    #  file: "newSubsystem.yml"

commands:
    driveController:
      name: "tankDrive"
      subsystems:
        - "driveTrain"
      default-sub: "driveTrain"